// This file was generated by gir (https://github.com/gtk-rs/gir @ a6737c7)
// from gir-files (https://github.com/gtk-rs/gir-files @ ???)
// DO NOT EDIT

use glib::translate::*;
use glib::GString;
use ibus_sys;
use libc;
use std::mem;


//pub fn accelerator_name(accelerator_key: u32, accelerator_mods: /*Ignored*/ModifierType) -> Option<GString> {
//    unsafe { TODO: call ibus_sys:ibus_accelerator_name() }
//}

//#[cfg(any(feature = "v1_5_18", feature = "dox"))]
//pub fn accelerator_parse(accelerator: &str) -> (u32, /*Ignored*/ModifierType) {
//    unsafe { TODO: call ibus_sys:ibus_accelerator_parse() }
//}

//pub fn accelerator_valid(keyval: u32, modifiers: /*Ignored*/ModifierType) -> bool {
//    unsafe { TODO: call ibus_sys:ibus_accelerator_valid() }
//}

//pub fn attr_background_new(color: u32, start_index: u32, end_index: u32) -> /*Ignored*/Option<Attribute> {
//    unsafe { TODO: call ibus_sys:ibus_attr_background_new() }
//}

//pub fn attr_foreground_new(color: u32, start_index: u32, end_index: u32) -> /*Ignored*/Option<Attribute> {
//    unsafe { TODO: call ibus_sys:ibus_attr_foreground_new() }
//}

//pub fn emoji_dict_load(path: &str) -> /*Unknown conversion*//*Unimplemented*/HashTable TypeId { ns_id: 0, id: 28 }/TypeId { ns_id: 0, id: 25 } {
//    unsafe { TODO: call ibus_sys:ibus_emoji_dict_load() }
//}

//pub fn emoji_dict_lookup(dict: /*Unknown conversion*//*Unimplemented*/HashTable TypeId { ns_id: 0, id: 28 }/TypeId { ns_id: 1, id: 33 }, emoji: &str) -> /*Ignored*/Option<EmojiData> {
//    unsafe { TODO: call ibus_sys:ibus_emoji_dict_lookup() }
//}

//pub fn emoji_dict_save(path: &str, dict: /*Unknown conversion*//*Unimplemented*/HashTable TypeId { ns_id: 0, id: 28 }/TypeId { ns_id: 0, id: 25 }) {
//    unsafe { TODO: call ibus_sys:ibus_emoji_dict_save() }
//}

pub fn get_address() -> Option<GString> {
    unsafe {
        from_glib_none(ibus_sys::ibus_get_address())
    }
}

pub fn get_daemon_uid() -> libc::c_long {
    unsafe {
        ibus_sys::ibus_get_daemon_uid()
    }
}

pub fn get_language_name(_locale: &str) -> Option<GString> {
    unsafe {
        from_glib_full(ibus_sys::ibus_get_language_name(_locale.to_glib_none().0))
    }
}

pub fn get_local_machine_id() -> Option<GString> {
    unsafe {
        from_glib_none(ibus_sys::ibus_get_local_machine_id())
    }
}

pub fn get_socket_path() -> Option<GString> {
    unsafe {
        from_glib_none(ibus_sys::ibus_get_socket_path())
    }
}

pub fn get_timeout() -> i32 {
    unsafe {
        ibus_sys::ibus_get_timeout()
    }
}

pub fn get_untranslated_language_name(_locale: &str) -> Option<GString> {
    unsafe {
        from_glib_full(ibus_sys::ibus_get_untranslated_language_name(_locale.to_glib_none().0))
    }
}

pub fn get_user_name() -> Option<GString> {
    unsafe {
        from_glib_none(ibus_sys::ibus_get_user_name())
    }
}

pub fn init() {
    unsafe {
        ibus_sys::ibus_init();
    }
}

pub fn key_event_to_string(keyval: u32, modifiers: u32) -> Option<GString> {
    unsafe {
        from_glib_full(ibus_sys::ibus_key_event_to_string(keyval, modifiers))
    }
}

pub fn keyval_convert_case(symbol: u32) -> (u32, u32) {
    unsafe {
        let mut lower = mem::MaybeUninit::uninit();
        let mut upper = mem::MaybeUninit::uninit();
        ibus_sys::ibus_keyval_convert_case(symbol, lower.as_mut_ptr(), upper.as_mut_ptr());
        let lower = lower.assume_init();
        let upper = upper.assume_init();
        (lower, upper)
    }
}

pub fn keyval_from_name(keyval_name: &str) -> u32 {
    unsafe {
        ibus_sys::ibus_keyval_from_name(keyval_name.to_glib_none().0)
    }
}

pub fn keyval_name(keyval: u32) -> Option<GString> {
    unsafe {
        from_glib_none(ibus_sys::ibus_keyval_name(keyval))
    }
}

pub fn keyval_to_lower(keyval: u32) -> u32 {
    unsafe {
        ibus_sys::ibus_keyval_to_lower(keyval)
    }
}

pub fn keyval_to_unicode(keyval: u32) -> char {
    unsafe {
        from_glib(ibus_sys::ibus_keyval_to_unicode(keyval))
    }
}

pub fn keyval_to_upper(keyval: u32) -> u32 {
    unsafe {
        ibus_sys::ibus_keyval_to_upper(keyval)
    }
}

pub fn main() {
    unsafe {
        ibus_sys::ibus_main();
    }
}

pub fn quit() {
    unsafe {
        ibus_sys::ibus_quit();
    }
}

pub fn set_display(display: &str) {
    unsafe {
        ibus_sys::ibus_set_display(display.to_glib_none().0);
    }
}

pub fn set_log_handler(verbose: bool) {
    unsafe {
        ibus_sys::ibus_set_log_handler(verbose.to_glib());
    }
}

pub fn unicode_to_keyval(wc: char) -> u32 {
    unsafe {
        ibus_sys::ibus_unicode_to_keyval(wc.to_glib())
    }
}

pub fn unset_log_handler() {
    unsafe {
        ibus_sys::ibus_unset_log_handler();
    }
}

pub fn write_address(address: &str) {
    unsafe {
        ibus_sys::ibus_write_address(address.to_glib_none().0);
    }
}
